# Problem

In economics, the Cobb-Douglas functional form of production functions is widely used to represent the relationship of an output to inputs. it was proposed by Knut Wicksell (1851 - 1926), and tested again statistical evidence by Charles Cobb and Paul Douglas in 1928. In 1928 Charles Cobb and Paul Douglas published a study in which they modeled the growth of the American economy during the period 1899-1922. They considered a simplified view of the economy in which production output is determined by the amount of labor involved and the amount of capital invested:

${ P(L,K) = bL^ \alpha K^ {1-\alpha} }$

${P}$ : total production (the monetary value of all goods produced in a year)   
${L}$: labor input (the total number of person-hours worked in a year)  
${K}$: capital input (the monetary worth of all machinery, equipment, and buildings)  
${b}$: total factor productivity  
${\alpha}$: the output elasticities of labor  

# Questions

## Using the data about the American economy in the table to find out ${b}$ and ${\alpha}$

The equatation can be re-written as:  
${log(P) = log(b) + \alpha log(L) + (1-\alpha)log(K) = log(b) + \alpha (log(L) - log(K)) + log(K) }$   
${log(P) - log(K) = log(b) + \alpha (log(L) - log(K))}$  
Then:  
${y = log(P) - log(K)}$  
${x = log(L) - log(K)}$

In [1]:
import tensorflow as tf
import numpy as np

### The data with columns: P, L, K

In [3]:
origin_data = np.array([[100,100,100],
                 [101,105,107],
                 [112,110,114],
                 [122,117,122],
                 [124,122,131],
                 [122,121,138],
                 [143,125,149],
                 [152,134,163],
                 [151,140,176],
                 [126,123,185],
                 [155,143,198],
                 [159,147,208],
                 [153,148,216],
                 [177,155,226],
                 [184,156,236],
                 [169,252,244],
                 [189,156,266],
                 [225,183,298],
                 [227,198,335],
                 [223,201,366],
                 [218,196,387],
                 [231,194,407],
                 [179,146,417],
                 [240,161,431]])
transform_data = np.log(origin_data)
print(transform_data)

[[4.60517019 4.60517019 4.60517019]
 [4.61512052 4.65396035 4.67282883]
 [4.71849887 4.70048037 4.73619845]
 [4.80402104 4.76217393 4.80402104]
 [4.82028157 4.80402104 4.87519732]
 [4.80402104 4.79579055 4.92725369]
 [4.96284463 4.82831374 5.00394631]
 [5.02388052 4.8978398  5.0937502 ]
 [5.01727984 4.94164242 5.170484  ]
 [4.83628191 4.81218436 5.22035583]
 [5.04342512 4.96284463 5.28826703]
 [5.0689042  4.99043259 5.33753808]
 [5.03043792 4.99721227 5.37527841]
 [5.17614973 5.04342512 5.420535  ]
 [5.21493576 5.04985601 5.46383181]
 [5.12989871 5.52942909 5.49716823]
 [5.24174702 5.04985601 5.58349631]
 [5.4161004  5.20948615 5.69709349]
 [5.42495002 5.28826703 5.81413053]
 [5.40717177 5.30330491 5.90263333]
 [5.38449506 5.27811466 5.95842469]
 [5.44241771 5.26785816 6.00881319]
 [5.18738581 4.98360662 6.03308622]
 [5.48063892 5.08140436 6.06610809]]


In [87]:
# y = log(P) - log(K)
y_data = transform_data[:,0:1] - transform_data[:,2:]
print(y_data, y_data.shape)

# x = log(L) - log(K)
X_data = transform_data[:,1:2] - transform_data[:,2:]
# Append x_0=1 to x
X_data = np.append(np.tile(np.array([1]),(X_data.shape[0],1)), X_data, axis=1)
print(X_data, X_data.shape)

[[ 0.        ]
 [-0.05770832]
 [-0.01769958]
 [ 0.        ]
 [-0.05491576]
 [-0.12323264]
 [-0.04110168]
 [-0.06986968]
 [-0.15320416]
 [-0.38407392]
 [-0.24484191]
 [-0.26863388]
 [-0.34484049]
 [-0.24438527]
 [-0.24889605]
 [-0.36726951]
 [-0.34174929]
 [-0.28099308]
 [-0.38918051]
 [-0.49546156]
 [-0.57392963]
 [-0.56639547]
 [-0.84570042]
 [-0.58546917]] (24, 1)
[[ 1.          0.        ]
 [ 1.         -0.01886848]
 [ 1.         -0.03571808]
 [ 1.         -0.04184711]
 [ 1.         -0.07117628]
 [ 1.         -0.13146314]
 [ 1.         -0.17563257]
 [ 1.         -0.1959104 ]
 [ 1.         -0.22884157]
 [ 1.         -0.40817147]
 [ 1.         -0.3254224 ]
 [ 1.         -0.34710549]
 [ 1.         -0.37806613]
 [ 1.         -0.37710988]
 [ 1.         -0.4139758 ]
 [ 1.          0.03226086]
 [ 1.         -0.5336403 ]
 [ 1.         -0.48760733]
 [ 1.         -0.5258635 ]
 [ 1.         -0.59932843]
 [ 1.         -0.68031003]
 [ 1.         -0.74095503]
 [ 1.         -1.0494796 ]
 [ 1.     

### Theta is ( ${log(b)}$, ${\alpha}$ )

In [88]:
theta = tf.Variable([[1],[2]], dtype=tf.float32)
print(theta.shape)

(2, 1)


In [89]:
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [91]:
cost = tf.reduce_sum(tf.pow(tf.matmul(X, theta)-y, 2))/(2*y_data.shape[0])

In [93]:
print(session.run(tf.matmul(X, theta)-y_data, feed_dict={X: X_data}))

[[ 1.        ]
 [ 1.0199714 ]
 [ 0.94626343]
 [ 0.9163058 ]
 [ 0.9125632 ]
 [ 0.8603064 ]
 [ 0.68983656]
 [ 0.6780489 ]
 [ 0.695521  ]
 [ 0.56773096]
 [ 0.5939971 ]
 [ 0.57442284]
 [ 0.5887083 ]
 [ 0.4901655 ]
 [ 0.42094445]
 [ 1.4317912 ]
 [ 0.27446863]
 [ 0.3057784 ]
 [ 0.33745345]
 [ 0.29680476]
 [ 0.21330959]
 [ 0.08448535]
 [-0.25325876]
 [-0.38393825]]


In [139]:
train = tf.train.GradientDescentOptimizer(0.001).minimize(cost)
init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)

In [206]:
num_iterations = 10000
for _ in range(num_iterations):
    session.run(train, feed_dict={X: X_data, y: y_data})
print(session.run(theta))

[[0.00700559]
 [0.77858937]]


## Result:
${log(b) = 0.00700559 <=> b = e^{0.00700559} = 1.007}$  
${\alpha = 0.77858937}$